baseURL = "https://theroutingclub.github.io/"
languageCode = "en-us"
title = "The Routing Club"
theme = "hugo-clarity"

[params]
  # directory(s) where your articles are located
  mainSections = ["posts"] # see config details here https://gohugo.io/functions/where/#mainsections
  # SidebarRecentLimit = 5
  # enableSearch = true
  logo = "logofiles/trclogo.png"
  # centerLogo = true
  # showShareButtons = true
  # ShowPostNavLinks = true
  introDescription = "Network Engineer, CCIE RS, ACI"
  introURL = "about/" # set the url for the 'read more' button below the introDescription, or set to false to not show the button  
  # Customize Sidebar Disclaimer Text
  sidebardisclaimer = true
  disclaimerText = "The opinions expressed on this site are my own personal opinions and do not represent my employer’s view in any way."
  
  # Show related content at the end of an article based on the 'series' taxonomy. Can be set in post front matter.
  # showRelatedInArticle = false
  # showRelatedInSidebar = false
  
  # customize footer icon. see issue https://github.com/chipzoller/hugo-clarity/issues/77
  footerLogo = ""

  # tell hugo where you store your icons e.g favicons. This is useful if you're using an apache server and there are conflicts >> see issue https://github.com/chipzoller/hugo-clarity/issues/74. If this is applicable to you, be sure to copy the contents of https://github.com/chipzoller/hugo-clarity/tree/master/static/icons to your preferred icons directory
  # iconsDir = "icons/" # without a leading forward slash  
  
  [params.author]
    name = "Nilesh Gore"
    # photo = "images/jane-doe.png" #include this if you would like to show the author photo on the sidebar

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.tableOfContents]
    endLevel = 10
    ordered = false
    startLevel = 1

[menu]
[[menu.main]]
  identifier = 'Home'
  name = 'Home'
  url = 'posts/'
  weight = 10
[[menu.main]]
  identifier = 'About'
  name = 'About'
  url = '/about/'
  weight = 20

# social menu links

[[menu.social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/nileshgore25"
# [[menu.social]]
#   name = "twitter"
#   weight = 2
#   url = "https://twitter.com/#"
[[menu.social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/nileshgore"
[[menu.social]]
  name = "email"
  weight = 4

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"  